const englishLettersFreq = new Object();
//Percentage of occurances in the English Language
englishLettersFreq['A'] = 8.2; 
englishLettersFreq['B'] = 1.5;
englishLettersFreq['C'] = 2.81;
englishLettersFreq['D'] = 4.3;
englishLettersFreq['E'] = 12.7;
englishLettersFreq['F'] = 2.2;
englishLettersFreq['G'] = 2.1;
englishLettersFreq['H'] = 6.1;
englishLettersFreq['I'] = 7.0;
englishLettersFreq['J'] = 0.2;
englishLettersFreq['K'] = 0.8;
englishLettersFreq['L'] = 4.0;
englishLettersFreq['M'] = 2.4;
englishLettersFreq['N'] = 6.7;
englishLettersFreq['O'] = 7.5;
englishLettersFreq['P'] = 1.9;
englishLettersFreq['Q'] = 0.12;
englishLettersFreq['R'] = 6.0;
englishLettersFreq['S'] = 6.3;
englishLettersFreq['T'] = 9.1;
englishLettersFreq['U'] = 2.8;
englishLettersFreq['V'] = 1.0;
englishLettersFreq['W'] = 2.3;
englishLettersFreq['X'] = 0.11;
englishLettersFreq['Y'] = 2.0;
englishLettersFreq['Z'] = 0.10;

export{englishLettersFreq};